{{- if not (lookup "v1" "ConfigMap" .Release.Namespace "fastfood-config") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | default "5432" | quote }}
  POSTGRES_DB_PEDIDOS: {{ .Values.postgres.db | quote }}
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"
{{- end -}}