apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.credentials.user }}"
  POSTGRES_PASSWORD: "{{ .Values.credentials.password }}"