{{- if not (lookup "v1" "Secret" .Release.Namespace "db-credentials-pedidos") -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-pedidos
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.credentials.user }}"
  POSTGRES_PASSWORD: "{{ .Values.credentials.password }}"
  JwtSettings--SecretKey: "{{ .Values.credentials.jwtSecret }}"
  SaltKey: "{{ .Values.credentials.saltKey }}"
{{- end -}}